//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragoMcLaren
{
    using System;
    using System.Collections.Generic;
    
    public partial class АвтомобилиИЗапчасти
    {
        public int IDАИЗ { get; set; }
        public Nullable<int> IDАвтомобиля { get; set; }
        public Nullable<int> IDЗапчасти { get; set; }
        public Nullable<int> НеобходимоеКоличество { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Запчасти Запчасти { get; set; }
    }
}
