//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragoMcLaren
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Клиенты()
        {
            this.Продажи = new HashSet<Продажи>();
            this.СервисныеВизиты = new HashSet<СервисныеВизиты>();
            this.ТестДрайвы = new HashSet<ТестДрайвы>();
            this.ФинансовыеУсловия = new HashSet<ФинансовыеУсловия>();
        }
    
        public int IDКлиента { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Телефон { get; set; }
        public string Адрес { get; set; }
        public string Город { get; set; }
        public string Страна { get; set; }
        public Nullable<int> IDПользователя { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СервисныеВизиты> СервисныеВизиты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТестДрайвы> ТестДрайвы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ФинансовыеУсловия> ФинансовыеУсловия { get; set; }
    }
}
