//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragoMcLaren
{
    using System;
    using System.Collections.Generic;
    
    public partial class СкладАвтомобилей
    {
        public int IDЗаписиНаСкладе { get; set; }
        public Nullable<int> IDАвтомобиля { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Местоположение { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
    }
}
