//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragoMcLaren
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.СервисныеВизиты = new HashSet<СервисныеВизиты>();
        }
    
        public int IDСотрудника { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Должность { get; set; }
        public Nullable<System.DateTime> ДатаНайма { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public Nullable<int> IDПользователя { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СервисныеВизиты> СервисныеВизиты { get; set; }
    }
}
