//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragoMcLaren
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТестДрайвы
    {
        public int IDТестДрайва { get; set; }
        public Nullable<int> IDКлиента { get; set; }
        public Nullable<int> IDАвтомобиля { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Продолжительность { get; set; }
        public Nullable<int> IDСотрудника { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
