//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragoMcLaren
{
    using System;
    using System.Collections.Generic;
    
    public partial class ФинансовыеУсловия
    {
        public int IDФинансирования { get; set; }
        public Nullable<int> IDКлиента { get; set; }
        public Nullable<int> IDАвтомобиля { get; set; }
        public Nullable<decimal> ПервоначальныйВзнос { get; set; }
        public Nullable<decimal> ЕжемесячныйПлатеж { get; set; }
        public Nullable<int> Срок { get; set; }
        public Nullable<double> ПроцентнаяСтавка { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
